# Generated by Django 4.2.6 on 2023-10-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles'),
        ),
    ]
