# Generated by Django 4.2.6 on 2023-10-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_userfollows_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='ticket'),
        ),
    ]
