# Generated by Django 4.2.6 on 2023-10-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_ticket_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='ticket/'),
        ),
    ]
