# Generated by Django 4.2.6 on 2023-10-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_ticket_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='thumbnail',
            field=models.ImageField(height_field=50, upload_to='ticket/', width_field=50),
        ),
    ]
