# Generated by Django 4.2.6 on 2023-11-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_ticket_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
