# Generated by Django 4.2.6 on 2023-11-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_review_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Critique'},
        ),
    ]
