# Generated by Django 4.2.6 on 2023-11-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-last_update'], 'verbose_name': 'Critique'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-last_update']},
        ),
    ]
